### PR TITLE
Add a tutorial for using debuggers

### PR DESCRIPTION
**Pull request by naotaco**
Debugging with hardware debuggers is mentioned in the book (https://rust-embedded.github.io/book/start/hardware.html) , but it's not work on RPi3 as is. I think filling the gap will be good help for beginners. 

This tutorial codes can be tested by following instructions on `README.md`.

And, please point out if you find any errors/wired sentences...

Thanks,

### CODE REVIEW

**Comment by andre-richter** [comment]
Oh wow, thanks a lot for that :pray:
This will be very useful indeed. I thought about HW debugging every now and then, but was to lazy to pursue it yet :)

I just ordered the Olimex hardware and will try this myself once I get it. Please have patience with me until I could test it, then I'll review the pull request and we can decide where to insert the tutorial.

Thanks,
Andre

**Comment by naotaco** [comment]
Thank you Andre!

I didn't know that we need `Waiting DHL` label on GitHub :)

**Comment by andre-richter** [comment]
We should put openocd into the docker container along with the other tools that are already there If that's possible, so the user has no hassles with installation/compilation.

**Comment by naotaco** [comment]
Thanks for suggestion. It sounds nice. I made and push a docker image and updated `README.md` to use it. Hopefully it works.

**Comment by andre-richter** [comment]
Hi @naotaco,

so I had the chance today to briefly try it out and it worked like a charm. Pretty awesome, thanks for paving the way.

Going further, I pondered a bit about how to integrate this tutorial in the right place.
Currently, my idea is the following:

1. I will add this as the new tutorial 0B, shifting the others back.
2. Your Docker version worked flawlessly. I will therefore add openocd to https://github.com/andre-richter/docker-raspi3-utils, the Docker container that is already in use for these tutorials.

There's a few more ideas in my head which I have yet to decide on. All this means that I will most probably not take your pull request as is, but push my revised version.
However, this means that you don't get credit by means of showing up in the commit history. Of course must be credited for all this properly. So I will do that in all the necessary places, like copyright headers etc. I will also add to the README and the tutorial prose that all this originates from you and link to your account.
I will let you review what I have in mind as a pull request once I'm ready, but it might take a few days until I'm there.

Kindly tell me if this approach is okay for you?

Thanks,
Andre

**Comment by andre-richter** [comment]
In case you are happy with the approach, you could help me with the following:

Accompanying the wiring table, I'd like to have something similar to https://github.com/rust-embedded/rust-raspi3-OS-tutorials/blob/master/doc/wiring.png for the Olimex wiring in the tutorials.

If you feel like it, you could have a look if there's resources for generating this in fritzing.

**Comment by naotaco** [comment]
Hi @andre-richter 

Thank you for testing. I'm happy to hear it works!

And thanks again for taking time to think how it'll be migrated.

> I will add this as the new tutorial 0B, shifting the others back.

I concern a bit about people already bookmarked or shared their URLs, but I also think a debugger section should not be very last part of tutorials... Anyway, it should follow your policy!

> Your Docker version worked flawlessly. I will therefore add openocd to https://github.com/andre-richter/docker-raspi3-utils, the Docker container that is already in use for these tutorials.

IMO, different tools should be in separated images to be version controlled independently; at least, HW debugger and qemu tools should be. In addition, (I just guess that) only a few people want to use both of them. It's good thing to reduce footprint of docker images at people who use only one tool. How about adding each tools under this repository (or somewhere else public) separately like following?

```
rust-raspi3-OS-tutorials/
└── docker-utils
    ├── openocd
    │   └── Dockerfile
    └── qemu
        └── Dockerfile
```

To keep consistency is the most important thing in tutorials, and the best way for that is giving finishing touches to all codes and docs by your hands I think :)

However, I'm afraid that it seems that revising files without git log is not git-way honestly. This is a matter of taste, but I think commit log's cleanness is not so important relatively.  
Therefore, I'm happy if you take my branch locally and add commits to revise after my commit and push again (maybe as different branch). Is it acceptable for you? Please note that I never mind even if my files are entirely rewritten by your commit :smiley:

At last, the wiring diagram looks nice, I'll add it soon.

Thanks,
Nao

**Comment by andre-richter** [comment]
> IMO, different tools should be in separated images to be version controlled independently; at least, HW debugger and qemu tools should be. In addition, (I just guess that) only a few people want to use both of them. It's good thing to reduce footprint of docker images at people who use only one tool. How about adding each tools under this repository (or somewhere else public) separately like following?

That is a good idea. Will do this.

> However, I'm afraid that it seems that revising files without git log is not git-way honestly. This is a matter of taste, but I think commit log's cleanness is not so important relatively.
Therefore, I'm happy if you take my branch locally and add commits to revise after my commit and push again (maybe as different branch). Is it acceptable for you? Please note that I never mind even if my files are entirely rewritten by your commit smiley

Agreed. I will take your additions as a cherry-pick locally and add my stuff on top of it. This way you get proper credit in the commit logs.

Also, please bear with me if it will take another week or two. Being a bit short on free time lately.

**Comment by naotaco** [comment]
Thanks Andre, I look forward to see your work 🙏

**Comment by andre-richter** [comment]
Closing this in favor of #17 which contains these changes.

**Pull request closed without merging**
