### PR TITLE
+= note on enabling BOOT_UART on Raspi4

### PR DESCRIPTION
**Pull request by Darneas**

### CODE REVIEW

**Comment by andre-richter** [comment]
The documentation says that this is to enable debug output on that UART. Not 100% sure what that means. Does that mean videocore output?

I never enabled this on my pi4 explicitly. So either it was enabled by factory settings, or it might not be needed in my case 🤔

**Comment by Darneas** [comment]
I'm also unsure, unfortunately. I also get some garbled output after MiniPush started and before it pushes the binary. Maybe this is the debug output... the question is why it's not working without this.

Could you please check `vcgencmd bootloader_config` on your pi4? Maybe it is enabled on yours? For mine, I had to set `BOOT_UART=1` to make the chainloader work.

**Comment by andre-richter** [comment]
Okay. Will check.

I currently don't have a ready-to-go Linux image available, so it might take some days until I get to it.

**Comment by Darneas** [comment]
I just undid the change to test it and it works (without the garbled output). Strange, as I did not change other things. Before, my `kernel8.img` was overwritten (and zero sized eventually) every time I would run the MiniPush and it yielded a `Protocol Error`.

**Comment by andre-richter** [comment]
The Pi4 behaves strange in different ways for me too. The Pi3 seems much more reliable.

For example, I was unable to fix the frequency of the MiniUart. It would always dynamically scale it during runtime, no matter what many config.txt I had tried to not do that.

 Typical first instance bugs of a new HW generation I presume =/

**Pull request closed without merging**
