### PR TITLE
fix start4.elf file naming to boot on Raspi 4

### PR DESCRIPTION
**Pull request by Darneas**

### CODE REVIEW

**Comment by andre-richter** [comment]
Interesting. Does fixup4.dat keep the 4 in the file name? Is this documented somewhere?

**Comment by Darneas** [comment]
[This](https://www.raspberrypi.org/documentation/configuration/boot_folder.md) reads like the name in the SD card should not make a difference. Apparently, it does on my Raspberry Pi 4.

Still, in the tutorial your URI was pointing `start.elf` and not `start4.elf`, which makes a difference.

On my card, I have `start.elf` and `fixup4.dat`.

**Comment by andre-richter** [comment]
> Still, in the tutorial your URI was pointing start.elf and not start4.elf, which makes a difference.

Good find with the link, thanks.

Can you do a short test and delete start.elf from your SD card and see if it makes a difference? Asking because the documentation you pointed to strongly reads like it should be named `start4.elf` 🤔

**Comment by Darneas** [comment]
I can confirm that it must be called `start.elf`. If the file is called `start4.elf` it does not boot/allow chainloading.

I also checked what happens if both `start.elf` and `start4.elf` are deployed... doesn't work either. In my setup, the `start4.elf` from the original must be put on the SD card with the name of `start.elf`.

As I found that the Raspbian image has different files than currently on master, I also checked and used `start4.elf` and `fixup4.dat` from the `stable` branch, but nothing changed. Interestingly, the Raspbian image boots fine...

**Comment by andre-richter** [comment]
Thanks for checking. I just ran some experiments myself with files freshly downloaded using the links from the tutorial README, and can partly confirm:

|Files on SD card|Result|
|---|---|
|only `config.txt`|fails, yellow LED flashing|
|`config.txt` + `start4.elf` named `start4.elf`|fails, but yellow flashing gone|
|`config.txt` + `start4.elf` named `start.elf`|fails, but yellow flashing gone|
|`config.txt` + `start4.elf` named `start4.elf` + `dtb`|works|
|`config.txt` + `start4.elf` named `start.elf` + `dtb`|works|

So, your and my RPi4 seem to behave differently wrt to what happens when the file is named `start4.elf`. I'll take your PR and change the notification sentence slightly.

Thanks for raising this issue, that was very helpful to enable more people using the tutorials.

**Comment by Darneas** [comment]
Agreed, you‘re welcome. Thanks for the awesome and accessible tutorial!

**Pull request merged**
